# Generated by Django 5.1.4 on 2025-01-29 06:18

import cajero.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('catalogo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_catalogo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nombre_item', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'catalogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('numero_cuenta', models.CharField(blank=True, default=cajero.models.AccountNumberSequence.get_next_account_number, max_length=10, unique=True)),
            ],
            options={
                'db_table': 'cuentas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('tarjeta_id', models.AutoField(primary_key=True, serialize=False)),
                ('pin', models.CharField(max_length=4)),
                ('pin_cambiado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('transaccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transacciones',
                'managed': False,
            },
        ),
    ]
